FROM python:3.9.10
WORKDIR /var/jenkins_home/workspace/BeTravelic/backend
COPY requirements.txt ./

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install django

RUN curl -s https://raw.githubusercontent.com/koshort/peunjeon/master/scripts/mecab.sh

# Install eunjeon / eunjeon을 설치합니다.
RUN pip3 install eunjeon

# RUN python-mecab-ko --version
RUN pip3 install eunjeon
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
EXPOSE 8080