FROM python:3.9.10
WORKDIR /var/jenkins_home/workspace/BeTravelic/backend
COPY requirements.txt ./

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install django

# RUN pip3 install libmecab-dev
# RUN pip3 install mecab-config
RUN pip3 install python-mecab-ko
RUN pip3 install mecab

# RUN python-mecab-ko --version
RUN pip3 install eunjeon
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
EXPOSE 8080