# Generated by Django 3.2 on 2022-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('content_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=500)),
                ('mapx', models.CharField(max_length=45)),
                ('mapy', models.CharField(max_length=45)),
                ('score', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('overview', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendFeed',
            fields=[
                ('recommend_feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(blank=True, max_length=500, null=True)),
                ('image_x', models.CharField(blank=True, max_length=500, null=True)),
                ('image_y', models.CharField(blank=True, max_length=500, null=True)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.CharField(max_length=45)),
                ('visited_at', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'recommendfeed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendPlace',
            fields=[
                ('recommend_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=500)),
                ('mapx', models.CharField(max_length=45)),
                ('mapy', models.CharField(max_length=45)),
                ('score', models.IntegerField()),
                ('overview', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'recommendplace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendUser',
            fields=[
                ('recommend_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'recommenduser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_code', models.IntegerField()),
                ('do_gwangyuksi', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('visited_at', models.CharField(max_length=45)),
                ('review_like', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewlike',
            fields=[
                ('like_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'review_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('Survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surveycategory', models.CharField(max_length=45)),
                ('surveykeyword', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=45)),
                ('pw', models.CharField(max_length=45)),
                ('refresh_token', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlace',
            fields=[
                ('visited_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_place',
                'managed': False,
            },
        ),
    ]
