# Generated by Django 4.1.1 on 2022-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendPlace',
            fields=[
                ('place_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=500)),
                ('mapx', models.CharField(max_length=45)),
                ('mapy', models.CharField(max_length=45)),
                ('score', models.IntegerField()),
                ('overview', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'recommendplace',
                'managed': False,
            },
        ),
    ]
