# Generated by Django 3.2 on 2022-09-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendFeed',
            fields=[
                ('recommend_feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(blank=True, max_length=500, null=True)),
                ('image_y', models.CharField(blank=True, max_length=500, null=True)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.CharField(max_length=45)),
                ('visited_at', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'recommendfeed',
                'managed': False,
            },
        ),
    ]
