import { Display } from "../../pages/MyPage";

export const dummyData = [
  {
    id: 1,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 2,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 3,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 4,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 5,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 6,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 7,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 8,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 9,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 10,
    fileName: null,
    x: 0,
    y: -150,
    width: "100%",
    height: "100%",
  },
  {
    id: 11,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 12,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 13,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 14,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 15,
    fileName: null,
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 16,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: 0,
    width: "100%",
    height: "100%",
  },
  {
    id: 17,
    fileName: "https://picsum.photos/500",
    x: 0,
    y: -250,
    width: "100%",
    height: "100%",
  },
];
